services:
  arangodb:
    image: arangodb:latest
    container_name: seminario-arango
    environment:
      - ARANGO_ROOT_PASSWORD=admin
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3

volumes:
  arango_data:
